### PR TITLE
Editorial: Fix minor typo "sytem"

### PR DESCRIPTION
**Pull request by mk-pmb**
***
<a href="https://whatpr.org/whatwg-fs/140.html" title="Last updated on Jul 24, 2023, 5:19 PM UTC (ddbb7c7)">Preview</a> | <a href="https://whatpr.org/fs/140/bee4f50...ddbb7c7.html" title="Last updated on Jul 24, 2023, 5:19 PM UTC (ddbb7c7)">Diff</a>

### CODE REVIEW

**Comment by a-sully** [comment]
Hi @mk-pmb, contributors to this repo need to sign the participant agreement. Please let me know which of the following options you prefer:

1. Sign the participant agreement, then we can merge this PR. Apologies for the burden, but once this is signed we welcome future contributions!
2. To get around this requirement for a trivial change like this, I can close this PR, make the change myself, and acknowledge you in the PR description

**Comment by mk-pmb** [comment]
Let's pick the easy (2nd) route.

**Comment by a-sully** [comment]
SGTM. Created #141

**Comment by mk-pmb** [comment]
On a side note, I was curious what the participant agreement would be. In the [WHATWG FAQ](https://whatwg.org/faq) I found the "participate" button which leads to https://participate.whatwg.org/ , but there I was blocked by CloudFlare. A futile annoyance, as I can still [read it on the Wayback Machine](https://web.archive.org/web/20230706034429/https://participate.whatwg.org/).
I know WHATWG somehow loves CloudFlare but I still believe they should use something that grants even suspicious people at least read-only access. Ideally something that also is not [a danger to the open internet](http://cryto.net/~joepie91/blog/2016/07/14/cloudflare-we-have-a-problem/).

**Pull request closed without merging**
