### PR TITLE
Add Acknowledgments

### PR DESCRIPTION
**Pull request by annevk**
This acknowledges everyone that contributed commits as well as those participating in the technical discussions leading up to the work moving to the WHATWG.

***
<a href="https://whatpr.org/fs/78.html" title="Last updated on Dec 3, 2022, 8:11 AM UTC (fe7d5a4)">Preview</a> | <a href="https://whatpr.org/fs/78/730e2ad...fe7d5a4.html" title="Last updated on Dec 3, 2022, 8:11 AM UTC (fe7d5a4)">Diff</a>

### CODE REVIEW

**Comment by annevk** [comment]
Please let me know if I have overlooked anyone.

cc @whatwg/storage @jesup

**Review by a-sully — APPROVED** [review]
LGTM if this looks good to @mkruisselbrink (there may be others from the early discussions who should be included that I'm not aware of)

**Comment by a-sully** [comment]
friendly ping @mkruisselbrink

**Review by mkruisselbrink — APPROVED** [review]
sorry for the delay, this looks like a pretty complete list to me

**Pull request merged**
